App/events/urls.py
from django.urls import path
from . import views
#Added 
app_name = 'home'

urlpatterns = [
    path('', views.homeView, name='home'),
    path('<int:id>/', views.eventDetailView, name='eventDetail'),
    path('<int:id>/edit/', views.eventEditView, name='eventEdit'),
]

App/profiles/urls.py
from django.urls import path
from . import views

app_name = 'profiles'

urlpatterns = [
    path('', views.profileView, name='profile'),
    path('edit/', views.editProfile, name='editProfile'),
]

App/source/urls.py
from django.urls import path
from .views import signUpView
from django.urls import include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('signup/',signUpView, name='signup'),
    path('home/', include('events.urls', namespace='events')),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    #For Password Reset
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App/events/models.py
from django.db import models
from profiles.models import Profile

# Create your models here.
class Event(models.Model):
    organizer   = models.ForeignKey(Profile, related_name='organizer', on_delete=models.CASCADE)
    attendees   = models.ManyToManyField(Profile, blank=True, default=None, related_name='attendees')
    title       = models.CharField(max_length=100)
    description = models.CharField(max_length=300)
    poster      = models.ImageField(upload_to='EventPoster/', blank=True)
    venue       = models.CharField(max_length=100)
    size        = models.PositiveIntegerField()
    price       = models.PositiveIntegerField()  
    updated     = models.TimeField(auto_now=True)
    created     = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.title}   -->  id : {self.id}" 
    
    class Meta:
        ordering = ('-created',)

App/events/forms.py
from django import forms
from .models import Event

class EventCreationForm(forms.ModelForm):
    class Meta:
        model  = Event
        fields = ['title', 'description', 'poster', 'venue', 'size', 'price']


class EventEditForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ['title', 'description', 'poster', 'venue', 'size', 'price']

App/events/views.py
import hashlib
from .models import Event
from django.template import loader
from profiles.models import Profile
from django.http import HttpResponse
from django.shortcuts import redirect
from django.core.mail import send_mail
from .forms import EventCreationForm, EventEditForm
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required
def homeView(request):
    profile = Profile.objects.get(user=request.user)
    form    = EventCreationForm(request.POST or None, request.FILES or None)
    events  = Event.objects.all()
    if request.method == 'POST':
        if form.is_valid():
            event = form.save(commit=False)
            event.organizer = profile  
            event.save()
            event.attendees.add(profile)  

            # Set a flag in the session to indicate a successful event creation
            request.session['eventCreated'] = True

    template = loader.get_template('events/home.html')
    context  = {
        "profile": profile,
        'form'   : form,
        'events' : events,
    }
    return HttpResponse(template.render(context, request))


@login_required
def eventDetailView(request, id):
    profile = Profile.objects.get(user=request.user)
    event   = Event.objects.get(pk=id)

    profileEmail   = profile.email 
    senderEmail    = "2004668@students.kcau.ac.ke"
    eventName      = event.title
    uuid           = generateUUID(profileEmail)
    profileSubject = f'Your UID for {eventName}'

    if request.method == 'POST':
        if profile not in event.attendees.all():
            sendUUID(profileSubject, senderEmail, profileEmail, uuid)
            event.attendees.add(profile)
            request.session['eventBooked'] = True

    template = loader.get_template('events/eventDetail.html')
    context = {
        'event'  : event,
        'profile': profile,
        'uuid'   : uuid,  
    }
    return HttpResponse(template.render(context, request))


def generateUUID(email):
    hashObject = hashlib.sha1(email.encode())
    hexDigit   = hashObject.hexdigest()
    uuid       = '-'.join([hexDigit[:3], hexDigit[4:7], hexDigit[8:11]])
    return uuid


def sendUUID(eventName, senderEmail, receiverEmail, uuid):
    subject = eventName
    message = f'Here is your 9-character UUID from the event organizer: {uuid}'
    send_mail(subject, message, senderEmail, [receiverEmail], fail_silently=False)


@login_required
def eventEditView(request, id):
    profile = Profile.objects.get(user=request.user)
    event   = Event.objects.get(pk=id)

    if request.method == 'POST':
        form = EventEditForm(request.POST, instance=event)
        if form.is_valid():
            form.save()
            return redirect('home:eventDetail', id=id)
    else:
        form = EventEditForm(instance=event)

    template = loader.get_template('events/eventEdit.html')
    context = {
        'event'   : event,
        'profile' : profile,
        'form'    : form,
    }
    return HttpResponse(template.render(context, request))

App/events/templates/events/eventDetail.html
<head>
  {% extends 'base.html' %}
  {% load static %}
  {% block title %}AstroEvents : {{event.id}}{% endblock title %}
</head>
{% block content %}
{% include 'events/navigationBar.html' %}
<div id="eventDetailsParent">

  <div class="ui card" id="eventDetailsParentCard">
    <div class="image"><img src={{event.poster.url}}></div>

    <div class="content">

      <a class="header">{{event.title}}</a>
      <div class="meta"><span class="date">{{event.venue}}</span></div>
      <div class="description">{{event.description}}</div>
     
      {% if event.attendees.count <= event.size %}
        <button class="ui secondary button" type="submit" id="eventDetailsBookBtn">Book Now</button>
      {% endif %}
    </div>
    
    <div class="extra content"><a><i class="user icon"></i>{{event.size}} Attendees</a></div>
    <div class="extra content"><a><i class="dollar sign icon"></i>{{event.price}}</a></div>
    
  </div>

  <div class="ui success message" id="eventDetailsMessage">
    <div class="header">Succcess !</div>
    <p>Event Succcessfully Booked</p>
  </div>

</div>

<div class="ui modal">
  <div class="header">Book Event</div>

  <form action="" method="POST" id="eventDetailForm" enctype="multipart/form-data">
    {% csrf_token %}

    <p>Thank you for choosing to book our event!</P>
    <p> Your reservation is almost complete. To finalize your booking, we'll send you a unique 9-character UID (Unique Identifier) via email.</P>
    <p>This UID is important and will help us identify your reservation.</P>

    <div class="actions">
      <div class="ui black deny button">Cancel</div>
      <button class="ui secondary button" type="submit">Book</button>
    </div>
  </form>
</div>
{% endblock content %}
{% block scripts %}
<script type="text/javascript">
  $(document).ready(function() {
    $('#eventDetailsBookBtn').click(function() {
      $('.ui.modal').modal('show');
    });
  });

  // Handle form submission via AJAX
  $('#eventDetailForm').submit(function(e) {

    e.preventDefault(); 
    var formData = $(this).serialize();

    $.ajax({
      type: 'POST',
      url : "{% url 'home:eventDetail' event.id %}",
      data: formData,
      success: function(response) {

        console.log('Form submitted successfully', response);

        $('#eventDetailsMessage').show();
        setTimeout(function() { $('#eventDetailsMessage').fadeOut('slow'); }, 5000);

      },
      error: function(error) { console.error('Error submitting form', error);  }
      
    });

    // Close the modal
    $('.ui.modal').modal('hide');
  });

</script>
{% endblock scripts %}

App/events/templates/events/eventEdit.html
<head>
    {% extends 'base.html' %}
    {% load static %}
    {% block title %}AstroEvents Edit : {{event.id}}{% endblock title %}
</head>
{% block content %}
{% include 'events/navigationBar.html' %}
<div id="eventEditParent">

    <h4 class="ui dividing header">Event Edit : {{event.title}}</h4>

    <form class="ui form" method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="two fields">
            <div class="field">
                <label>Title</label>
                {{form.title}}
            </div>
      
            <div class="field">
                <label>Description</label>
                {{form.description}}
            </div>
        </div>

        <div class="field">
            <label>Poster</label>
            {{form.poster}}
        </div>

        <div class="field">
            <label>Venue</label>
            {{form.venue}}
        </div>

        <div class="two fields">
            <div class="field">
                <label>Size</label>
                {{form.size}}
            </div>
    
            <div class="field">
                <label>Price</label>
                {{form.price}}
            </div>
        </div>

        <button class="ui button" type="submit">Done</button>
    </form>

</div>
{% endblock content %}
{% block scripts %}
<script type="text/javascript">

</script>
{% endblock scripts %}
  
  
  
  
  

App/events/templates/events/home.html
<head>
  {% extends 'base.html' %}
  {% load static %}
  {% block title %}AstroEvents{% endblock title %}
  {% load widget_tweaks %} 
</head>
{% block content %}
{% include 'events/navigationBar.html' %}
<div id="homeMainDiv">

  <div id="homeEventChildDiv">
    <button class="ui secondary button" id="homeCreateBtn">Create Event</button>

    <div class="ui success message" id="homeEventMessage">
      <div class="header">Succcess !</div>
      <p>Event Succcessfully Created</p>
    </div>
  </div>

  <div id="homeEventDiv">
    {% for event in events %}
      <div class="ui card" id="homeEventCard">
        <div class="image"><img src={{event.poster.url}}></div>

        <div class="content">

          <a class="header">{{event.title}}</a>
          <div class="meta"><span class="date">{{event.venue}}</span></div>
          <div class="description">{{event.description}}</div>
         
          <a class="item" href="{% url 'home:eventDetail' event.id %}">
            <button class="ui right labeled icon button" id="eventDetailBtn">
              <i class="add icon"></i>
              Details
            </button>
          </a>
        </div>
        
        <div class="extra content"><a><i class="user icon"></i>{{event.size}} Attendees</a></div>
        <div class="extra content"><a><i class="dollar sign icon"></i>{{event.price}}</a></div>
        
      </div>

    {% empty %}
      <div class="ui icon message">
        <i class="inbox icon"></i>
        <div class="content">
          <div class="header">Discover a World of Possibilities!</div>
          <p>While there are no events currently scheduled, our team is working diligently to bring you exciting and unforgettable experiences. </p>
        </div>
      </div>
    {% endfor %}
   
  </div>

</div>

<div class="ui modal">
  <div class="header">Create Event</div>

  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="ui form" id="homeeventCreateForm">

      <div class="field">
        <label>Title</label>
        {{form.title}}
      </div>

      <div class="field">
        <label>Description</label>
        {{form.description}}
      </div>

      <div class="field">
        <label>Poster</label>
        {{form.poster}}
      </div>

      <div class="field">
        <label>Venue</label>
        {{form.venue}}
      </div>

      <div class="field">
        <label>Size</label>
        {{form.size}}
      </div>

      <div class="field">
        <label>Price</label>
        {{form.price}}
      </div>

    </div>

    <div class="actions" id="eventActionBtns">
      <div class="ui black deny button">Cancel</div>
      <button class="ui secondary button" type="submit">Create</button>
    </div>
  </form>
</div>
{% endblock content %}
{% block scripts %}
<script type="text/javascript">
  $(document).ready(function() {
    $('#homeCreateBtn').click(function() {
      $('.ui.modal').modal('show');
    });
  });


  // Check if the session variable indicates a successful event creation
  var eventCreated = {% if request.session.eventCreated %}true{% else %}false{% endif %};

  if (eventCreated) {
    $('#homeEventMessage').show();
    setTimeout(function() {
      $('#homeEventMessage').fadeOut('slow');
    }, 5000);  // Hide after 5 seconds
  }
</script>
{% endblock scripts %}

App/events/templates/events/navigationBar.html
<head>
  {% load static %}
</head>
{% block content %}
<div class="ui secondary pointing menu" id="navbarMainDiv">
  <a class="item" href="{% url 'events:home' %}"><b>Home</b></a>
  <a class="item" href="{% url 'profiles:profile' %}" ><b>{{profile.user}}</b></a>
  <a class="item" href="{% url 'login' %}"><b>Log Out</b></a>
</div>
{% endblock content %}
{% block scripts %}
<script type="text/javascript">
$('.item').click(function() {
  $('.item').eq(1).click();
});
</script>
{% endblock scripts %}