App/events/urls.py
from django.urls import path
from . import views
#Added 
app_name = 'home'

urlpatterns = [
    path('', views.homeView, name='home'),
    path('<int:id>/', views.eventDetailView, name='eventDetail'),
    path('<int:id>/edit/', views.eventEditView, name='eventEdit'),
]

App/profiles/urls.py
from django.urls import path
from . import views

app_name = 'profiles'

urlpatterns = [
    path('', views.profileView, name='profile'),
    path('edit/', views.editProfile, name='editProfile'),
]

App/source/urls.py
from django.urls import path
from .views import signUpView
from django.urls import include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('signup/',signUpView, name='signup'),
    path('home/', include('events.urls', namespace='events')),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    #For Password Reset
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App/profiles/models.py
from .utils import get_uuid
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify

# Create your models here.
class Profile(models.Model):
    user           = models.OneToOneField(User, on_delete=models.CASCADE)
    slug           = models.SlugField(unique=True, blank=True)
    profilePicture = models.ImageField(default='userPlaceHolder.png', upload_to='ProfilePictures')
    firstName      = models.CharField(max_length=35, blank=True)
    lastName       = models.CharField(max_length=35, blank=True)
    email          = models.EmailField(max_length=90, blank=True)
    updated        = models.TimeField(auto_now=True)
    created        = models.TimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username}   -->  Email : {self.user.email}"

    def save(self, *args, **kwargs):
        instance = False
        if self.user.email:
            sluged = slugify(str(self.user.username))
            instance = Profile.objects.filter(slug=sluged).exists()

            while instance:
                sluged = slugify(sluged + " " + str(get_uuid()))
                instance = Profile.objects.filter(slug=sluged).exists()

                self.slug  = sluged
                self.email = self.user.email  
        else:
            sluged = str(self.user)
        self.slug = sluged
        super().save(*args, **kwargs)

App/profiles/forms.py
from django import forms
from .models import Profile

class EditForm(forms.ModelForm):
    firstName = forms.CharField(required=False, widget=forms.TextInput(attrs={'placeholder' : 'First Name'}))
    lastName  = forms.CharField(required=False, widget=forms.TextInput(attrs={'placeholder' : 'Last Name'}))
    email     = forms.EmailField(required=False, widget=forms.TextInput(attrs={'placeholder' : 'Email',}))

    class Meta:
        model   = Profile
        fields  = ('profilePicture', 'firstName', 'lastName', 'email')
        widgets = {'profilePicture' : forms.FileInput(attrs={})}

App/profiles/views.py
from .models import Profile
from .forms import EditForm
from events.models import Event
from django.template import loader
from django.http import HttpResponse
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required

@login_required
def profileView(request):
    profile       = Profile.objects.get(user=request.user)
    profileEvents = Event.objects.filter(organizer=profile)
    template      = loader.get_template('profiles/profile.html')
    context  = {
        'profile'       : profile,
        'profileEvents' : profileEvents,
    }
    return HttpResponse(template.render(context, request))


@login_required
def editProfile(request):
    profile  = Profile.objects.get(user=request.user)
    form     = EditForm(request.POST or None, request.FILES or None, instance=profile)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('profiles:profile')
    template = loader.get_template('profiles/editProfile.html')
    context = {
        'profile':profile,
        'form'   :form,
    }
    return HttpResponse(template.render(context, request))

App/profiles/templates/profiles/editProfile.html
<head>
    {% extends 'base.html' %}
    {% load static %}
    {% block title %}AstroEvents | edit {{profile}}{% endblock title %}   
</head>
{% block content %}
{% include 'events/navigationBar.html' %}
<div class="ui segment" id="profileEditParent">
  <form action="" method="POST" enctype="multipart/form-data" class="ui form" id="profileEditCard">
    {% csrf_token %}
    <h4 class="ui dividing header">Profile Information</h4>
    <div class="field">
      <div id="profileEditCardChild">
        <img class="ui medium circular image" id="profileEditProfileIcon" src={{profile.profilePicture.url}}>
        <div class="field">{{form.profilePicture}}</div>
      </div>
      
      <label>Name</label>
      <div class="two fields">
        <div class="field">{{form.firstName}}</div>
        <div class="field">{{form.lastName}}</div>
      </div>
      <label>Email & Phone Number</label>
      <div class="two fields">
        <div class="field">{{form.email}}</div>
      </div>
    </div>
    <button class="ui primary button" type="submit">Save</button>
  </form>
</div>
{% endblock content %}
{% block scripts %}
<script type="text/javascript">

</script>
{% endblock scripts %}

App/profiles/templates/profiles/profile.html
<head>
    {% extends 'base.html' %}
    {% load static %}
    {% block title %}AstroEvents | {{profile}}{% endblock title %}   
</head>
{% block content %}
{% include 'events/navigationBar.html' %}
<div class="ui link cards" id="profileParentDiv">
    <div class="card" id="profileCard">
        <div class="image">
            <img src={{profile.profilePicture.url}}>
        </div>
        <div class="content">
            <div class="header">{{profile.firstName}}  {{profile.lastName}} </div>
            <div class="meta"><a>{{profile.email}}</a></div>
        </div>

        <div class="extra content">
            <button class="ui basic button" onclick="profileEdit()">
                <i class="icon user"></i>Edit Profile
            </button>
        </div>
    </div>

    <div id="profileEvents">
        {% for event in profileEvents %}
        <div class="ui card" id="profileEventsCard">
            <div class="image"><img src={{event.poster.url}}></div>
    
            <div class="content">
    
              <a class="header">{{event.title}}</a>
              <div class="meta"><span class="date">{{event.venue}}</span></div>
              <div class="description">{{event.description}}</div>
             
                <a class="item" href="{% url 'home:eventDetail' event.id %}">
                    <button class="ui right labeled icon button" id="eventDetailBtn">
                    <i class="add icon"></i>
                    Details
                    </button>
                </a>

                <a class="item" href="{% url 'home:eventEdit' event.id %}">
                    <button class="ui right labeled icon button" id="eventDetailBtn">
                        <i class="edit icon"></i>
                        Edit
                    </button>
                </a>
            </div>
            
            <div class="extra content"><a><i class="user icon"></i>{{event.size}} Attendees</a></div>
            <div class="extra content"><a><i class="dollar sign icon"></i>{{event.price}}</a></div>
            
          </div>
        {% endfor %}
    </div>

</div>
{% endblock content %}
{% block scripts %}
<script type="text/javascript">
    function profileEdit(){ window.location.href = "{% url 'profiles:editProfile' %}"; }
</script>
{% endblock scripts %}